name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          # Capture the current date in YYYY-MM-DD format
          current_date=$(date +'%Y-%m-%d')

          # Define the report filename with the date
          report_filename="YourCollectionName_${current_date}.html"

          newman run postman/daas_service_collection.json \
            -e postman/daas_service_env.json \
            --reporters cli,html,json \ 
            --reporter-html-export "newman/${report_filename}"

      - name: Upload Postman Report
        uses: actions/upload-artifact@v2
        with:
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws s3 cp newman/${report_filename} s3://grasp-service-monitoring
